name: Docker Image Build
on:
  push:
    paths:
      - ".github/workflows/docker-build.yaml"
      - "docker/**"
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}     

      - name: Build and push
        working-directory: docker
        run: |
          docker-compose build --pull
          docker-compose push

